# Generated by Django 4.1.3 on 2022-12-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0004_tweets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='location',
            field=models.TextField(default='location', max_length=100),
            preserve_default=False,
        ),
    ]
