# Generated by Django 4.1.3 on 2022-12-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0006_alter_tweets_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetquery',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
