# Generated by Django 4.1.3 on 2022-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0008_tweets_queryowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='cleaned_tweet',
            field=models.TextField(blank='True', max_length=280, null='True'),
            preserve_default='True',
        ),
    ]
