# Generated by Django 4.1.3 on 2022-12-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0009_tweets_cleaned_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetquery',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
