# Generated by Django 4.1.3 on 2022-12-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0010_tweetquery_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
    ]
