# Generated by Django 4.1.3 on 2022-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0011_tweets_like_count_tweets_retweet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
