# Generated by Django 4.1.3 on 2022-12-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0012_tweets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='context_annotations',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='entities',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
