# Generated by Django 4.1.3 on 2022-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0014_tweets_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='context_annotations',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
