# Generated by Django 4.1.3 on 2022-12-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0015_alter_tweets_context_annotations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='entities',
            new_name='followers_count',
        ),
    ]
