# Generated by Django 4.1.3 on 2022-12-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0018_alter_tweets_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
