# Generated by Django 4.1.3 on 2022-12-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominer', '0019_alter_tweets_followers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='annotations',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
